project:
  type: website

website:
  title: "E-tech Blog"
  favicon: et_logo.jpg
  site-url: https://e-tech-blog.netlify.app/
  open-graph: true
  navbar:
    logo: et_logo.jpg
    left:
      - href: research/index.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/Ellie190
      - icon: linkedin
        href: https://www.linkedin.com/in/eli-nimy-a752a1191/
      - icon: person-badge
        href: https://eli-nimy.netlify.app
      - icon: rss
        href: index.xml
  page-footer:
    left: "© 2024 Eli Nimy."
    right:
    - icon: linkedin
      href: https://www.linkedin.com/in/eli-nimy-a752a1191/
    - icon: envelope
      href: mailto:nimyellie0512@gmail.com
    - icon: github
      href: https://github.com/Ellie190
    - icon: person-badge
      href: https://eli-nimy.netlify.app
format:
  html:
    theme:
      light: flatly
      dark: darkly

editor: visual

